---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((corporate-harbor-registry))/((dockerhub-organization))/release-ci-image
    tag: master
inputs:
  - name: git-repo
  - name: artifactory-repo
params:
  SONATYPE_USERNAME:
  SONATYPE_PASSWORD:
  SONATYPE_STAGING_PROFILE_ID:
run:
  path: git-repo/ci/scripts/sync-to-maven-central.sh
